import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import MainNavClient from '@/components/client/nav/main/main-nav.component';
import '@/common/styles/globals.scss';
import styles from '@/app/page.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <header>
                    <MainNavClient />
                </header>
                <main className={styles.main}>{children}</main>
            </body>
        </html>
    );
}
