export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";


export const SELECT_SONG = "SELECT_SONG";


export const FETCH_POSTS = "FETCH_POSTS";


export const FETCH_FRAMEWORKS = "FETCH_FRAMEWORKS";
export const CHANGE_FRAMEWORK_STATUS = "CHANGE_FRAMEWORK_STATUS";


export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";


export const CREATE_STREAM = "CREATE_STREAM";
export const FETCH_STREAMS = "FETCH_STREAMS";
export const FETCH_STREAM = "FETCH_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";
export const EDIT_STREAM = "EDIT_STREAM";


export const SHOP_USER_TYPES = {
    SET_CURRENT_USER: "SET_CURRENT_USER"
};

export const SHOP_CART_TYPES = {
    TOGGLE_DROPDOWN: "TOGGLE_DROPDOWN",
    CLOSE_DROPDOWN: "CLOSE_DROPDOWN",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEMS: "REMOVE_ITEMS",
    REMOVE_ITEM: "REMOVE_ITEM",
    CLEAR_ITEMS: "CLEAR_ITEMS",
};

export const SHOP_DATA_TYPES = {
    SET_DATA: "SET_DATA"
};

