import { LevelEnum } from '../models/common.model';

export const ENGLISH_WORDS_DICTIONARY: Record<string, string | string[]> = {
    fair: 'светлый',
    down: 'пух',
    feather: 'перо',
    intent: 'намерение',
    intend: 'намереваться',
    exile: ['изгнание', 'изгонять'],
    expel: 'изгонять',
    straight: 'прямой',
    wavy: 'волнистый',
    bald: 'лысый',
    fine: 'прекрасно',
    fly: ['муха', 'летать'],
    hop: 'прыгать',
    toe: 'палец ноги',
    tot: 'малыш',
    ant: 'муравей',
    vest: 'жилетка',
    cave: 'пещера',
    insect: 'насекомое',
    nut: 'орех',
    indigo: 'тёмно-синий',
    'building set': 'строительный конструктор',
    fantastic: ['превосходный', 'чудесный'],
    ["I've got"]: 'у меня есть',
    ["Let's"]: 'Давай(те)',
    lovely: 'чудесный',
    slide: 'горка',
    swing: 'качели',
    answer: ['отвечать', 'ответ'],
    check: 'проверять',
    count: 'считать',
    listen: 'слушать',
    read: 'читать',
    revision: 'повторение',
    ['Come in!']: 'Входите!',
    for: 'для',
    ["Let's go"]: 'Пойдём',
    letter: ['буква', 'письмо'],
    autumn: 'осень',
    backpack: 'рюкзак',
    cool: ['классный', 'холодный'],
    crayon: 'цветной мелок',
    eraser: 'ластик',
    'glue tube': 'тюбик клея',
    nice: ['хороший', 'приятный'],
    ruler: 'линейка',
    sharpener: 'точилка',
    spring: 'весна',
    them: ['их', 'им'],
    they: 'они',
    too: 'тоже',
    use: 'использовать',
    ['Any questions?']: 'Есть вопросы?',
    ['Are you ready?']: 'Вы готовы?',
    ['Have a go!']: 'Попробуйте!',
    ['Next one, please']: ['Следующий, пожалуйста'],
    season: ['время года'],
    ['This is he']: ['это он'],
    ['These are them']: ['это они'],
    chair: 'стул',
    cupboard: 'шкаф',
    desk: ['парта', 'стол'],
    ['felt tip']: 'фломастер',
    in: 'в',
    on: 'на',
    scissors: 'ножницы',
    first: 'первый',
    second: 'второй',
    third: 'третий',
    shelf: 'полка',
    under: 'под',
    where: 'где',
    circle: ['обводить', 'круг'],
    cut: 'резать',
    draw: 'рисовать',
    type: ['печатать', 'набирать текст'],
    underline: 'подчёркивать',
    watch: 'смотреть',
    write: 'писать',
    borrow: ['взять на время', 'одолжить'],
    ['Here you are']: ['Вот, пожалуйста'],
    ['I need']: ['Мне нужно'],
    ['No problem']: ['Не за что'],
    ['Of course']: ['Конечно'],
    ['Thanks a lot']: ['Большое спасибо'],
    ['write down']: 'записать',
    ['word']: 'слово',
    ["You're welcome"]: 'пожалуйста',
    sure: 'конечно',
};

// внес 20 заданий

const MEDIUM_WORDS_DICTIONARY = {
    den: 'Логово/пещера/кабинет',
    capricious: 'капризный',
    exotic: 'экзотичный',
    inhibit: 'блокировать',
    minimum: 'минимальный',
    vulnerable: 'уязвимый',
    vanity: 'тщеславие',
    trending: 'Склоняться, иметь тенденцию',
    striking: 'поразительный',
    cumbersome: 'Громоздкий',
    'In bulk': 'Оптом навалом',
    Zealous: 'ревностный/рвение усердие',
    skit: 'Небольшая пародия',
    Medium: 'Среда (!)',
    incompetent: 'некомпетентный',
    improvisation: 'импровизация',
    hilarious: 'веселый',
    gala: 'Праздник, вечер',
    charismatic: 'харизматичный',
    cast: 'команда',
    amateurish: 'любительский',
    advent: 'прибытие',
    ambiguous: 'двусмысленный',
    connotation: 'Сопутствующее значение',
    decipher: 'Разгадывать распутывать',
    denote: 'обозначать',
    illiterate: 'неграмотный',
    ingenious: 'гениальный',
    inscription: 'надпись',
    phonetic: 'фонетический',
    symbolic: 'символичный',
    abstract: 'абстрактный',
    context: 'контекст',
    depict: 'Изображать описывать',
    dimension: 'измерение',
    esthetically: 'эстетично',
    intrinsic: 'Свойственный присущий',
    perspective: 'перспектива',
    portrayal: 'Изображение описание',
    realism: 'реализм',
    spectrum: 'спектр',
    antipathy: 'антипатия',
    arrogantly: 'уперто',
    berate: 'ругать',
    contemptuous: 'презрительный',
    despise: 'презирать',
    humiliation: 'унижение',
    obnoxious: 'отвратительный',
    'Shame (verb)': 'Ругать срамить',
    stigmatize: 'клеймить',
    vitriolic: 'саркастический',
    abandon: 'Бросать покидать',
    adversely: 'отрицательно',
    'aggregate (adj)': 'совокупный',
    fertilize: 'удобрять',
    intensify: 'усиливать',
    obtain: 'получать',
    precipitation: 'осадки',
    anticipate: 'предполагать',
    collide: 'сталкивать',
    famine: 'голод',
    impact: 'влиять',
    persevere: 'сохранять',
    plunge: 'погружать',
    unleash: 'отпускать',
    diverse: 'разнообразный',
    feature: 'особенность',
    inherent: 'свойственный',
    constraint: 'ограничивать',
    contamination: 'загрязнение',
    deplete: 'истощать',
    'dispose of': 'распоряжаться',
    emission: 'эмиссия',
    extinction: 'вымирание',
    shrink: 'Сокращаться / сжиматься',
    adjust: 'настраивать',
    arbitrary: 'Произвольный, случайный',
    denominator: 'знаменатель',
    infinitesimal: 'бесконечно малый',
    sequence: 'последовательность',
    accuracy: 'точность',
    adjacent: 'смежный',
    compress: 'сжимать',
    feasible: 'выполнимый',
    gut: 'потрошить',
    ['When it comes to (+…ing)']: 'когда речь заходит о…',
    ['that said']: 'здесь говорится',
    ['tend to']: 'иметь тенденцию',
    ['depending on']: 'в зависимости от.',
    ['To come into conflict with']: 'конфликтовать с',
    adolescent: 'подросток',
    cause: 'причина',
    delinquency: 'правонарушение',
    hedonistic: 'любящий наслаждения',
    hypocritically: 'лицемерно',
    ['To rebel against']: 'восставать против',
    ['Maintain the status quo']: 'оставлять в текущем состоянии',
};

export const ENGLISH_DICTIONARIES: Record<LevelEnum, Record<string, string | string[]>> = {
    [LevelEnum.Easy]: ENGLISH_WORDS_DICTIONARY,
    [LevelEnum.Medium]: MEDIUM_WORDS_DICTIONARY,
    [LevelEnum.Hard]: MEDIUM_WORDS_DICTIONARY,
    [LevelEnum.Expert]: MEDIUM_WORDS_DICTIONARY,
};
