version: '3.8'

services:
  frontend:
    image: nginx-frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

  backend:
    image: nginx-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - backend
  db:
      #      название контейнера
    container_name: db-frontend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:11.22-alpine3.18

networks:
  frontend:
  backend:
  db:
