# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

defaults:
    run:
        working-directory: ./client

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
#    клонирую свой репозиторий:
    - uses: actions/checkout@v3
    - name: Cache multiple paths
      uses: actions/cache@v3
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install --force
    - name: npm run build
      run: npm run build --if-present
#    - name: npm run e2e
#      run: npm run e2e --if-present
#    - name: npm run stylelint
#      run: npm run stylelint --if-present
#    - name: npm run unit
#      run: npm run unit --if-present
#    - name: npm run eslint
#      run: npm run eslint --if-present
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: client/build # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
#     - run: npm test
